version: "3.9"
services:
  team-website:
    restart: always
    image: team-website:latest
    hostname: team-website
    container_name: team-website
    networks:
      - external-net
    ports:
      - "8000:80"
networks:
  external-net:
    name: external-net
    external: true