version: "3.9"
services:
  invest-ideas-ui:
    restart: always
    image: devitforelead/invest-ideas-ui:latest
    hostname: invest-ideas-ui
    container_name: invest-ideas-ui
    environment:
      - VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      - VITE_SUPABASE_KEY: ${VITE_SUPABASE_KEY}
    networks:
      - external-net
    ports:
      - "3007:80"
networks:
  external-net:
    name: external-net
    external: true