version: "3.9"
services:
  invest-ideas:
    restart: always
    image: invest-ideas:latest
    hostname: invest-ideas
    container_name: invest-ideas
    networks:
      - external-net
    ports:
      - "3007:80"
networks:
  external-net:
    name: external-net
    external: true