name: Pipeline

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    name: BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (fast)
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Building image 🏗"
        run: |
          bash build.sh

      - name: Publishing image ...
        run: |
          chmod a+x publish
          bash publish push -f devitforelead/invest-ideas-ui -t latest

  deploy:
    name: DEPLOY
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "frontend"

      - name: Install SSH key of timeweb
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login -p ${{ secrets.DOCKER_PASSWORD }} -u ${{ secrets.DOCKER_USERNAME }}
            cd invest-ideas
            docker compose down
            set -a
            source .env
            set +a
            docker rmi devitforelead/invest-ideas-ui
            docker pull devitforelead/invest-ideas-ui
            docker compose up -d
            docker restart nginx